.PHONY: all clean
CC = gcc
CCFLAGS = -g -Wall -Werror -Wextra -pedantic


strace_0:
	$(CC) $(CCFLAGS) strace_0.c -o strace_0

strace_1:
	$(CC) $(CCFLAGS) strace_1.c -o strace_1


#clean
clean:
	rm -f strace_0 strace_1
