.PHONY: all clean
CC = gcc
CCFLAGS = -g -Wall -Werror -Wextra -pedantic


strace_0: clean
	$(CC) $(CCFLAGS) strace_0.c -o strace_0

strace_1: clean
	$(CC) $(CCFLAGS) strace_1.c -o strace_1

strace_2: clean
	$(CC) $(CCFLAGS) strace_2.c -o strace_2


#clean
clean:
	rm -f strace_0 strace_1 strace_2
